[brainflow]
git-tree-sha1 = "66f67bebce97d56b31229d6ec8e6f5b00fc75bda"
lazy = true

    [[brainflow.download]]
    sha256 = "dcfc69d6625b67903fc95d3be27de922c7533baba4971f4ae13539c52675fb05"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/5.10.1/compiled_libs.tar"
